[metadata]
name = anylog-api
version = 1.0.0 (new-os-dev - 64d1c3 [2026-03-26 16:39:38])
author = AnyLog Co.
contact = info@anylog.co
description = Tool for AnyLog / EdgeLake RESTfull API
license = Copyright AnyLog Co.
site = https://anylog.network
docs = https://github.com/AnyLog-co/documentation
source = https://github.com/AnyLog-co/AnyLog-API

[bdist_wheel]
universal = 1
