name: Python Unit Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  pull_request:
    branches:
      - '**'  # Trigger on PR to any branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Use the default GITHUB_TOKEN instead of a custom PAT
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest unit-testing/*.py -v --failfast

      # Optional: Remove this step if you're not uploading test results
      - name: Upload test results (optional)
        if: failure()  # Only run this step if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
dd